### ISSUE TITLE
registry.hub.docker.io URL

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#169] opened 2015-05-15 03:54 UTC
This is a question. I'm confused about the Docker registry. The documentation says:

> The server id must specify the registry to push to/pull from, which by default is central index `registry.hub.docker.io`.

Is this meant to be a URL? The following documentation suggests as much:

> The registry to push is by default `registry.hub.docker.io` but can be specified as part of the images's `name` name the Docker way. E.g. `docker.test.org:5000/data:1.5`

But then, is `registry.hub.docker.io` actually a/the right URL? I'm under the impression now that it doesn't work. During the tinkering that lead to issue #166 `registry.hub.docker.io` didn't seem to work for me, while `registry.hub.docker.com` *did* work for me (or more specifically: `registry.hub.docker.com/mysql:5.7`).

**Comment by rhuss** [comment] 2015-05-15 15:32
The first paragraph is about how to specify authentication. In my `~/.m2/setttings.xml` I have 

````xml
<servers>
  <server>
       <id>registry.hub.docker.io</id>
       <username>jolokia</username>
       <password>{zZ/00....}</password>
  </server>
</servers>
````

which works perfectly for pushing images to Docker Hub (i.e. images without registry as part of their name). 

What kind of error do you get when you use `registry.hub.docker.io` as registry in your servers.xml ?

**Comment by sverhagen** [comment] 2015-05-15 19:04
I don't mean to be confusing.

There's two issues:

 1. As described in #146, it appears that only `<servers>... <server>... <id>registry.hub.docker.io</id>...` is supported in `settings.xml`. The credentials even appear to be applied to my own server (which I reference from my `pom.xml` as `<registry>docker.company.com</registry>`. I had expected to add a `settings.xml` entry such as `<servers>... <server>... <id>docker.company.com</id>...`, but that didn't do anything. I now have in my `settings.xml` `<servers>... <server>... <id>registry.hub.docker.io</id>...` with user name/password for my own server, for the interim. Funky! But different issue (#146).

 2. As meant in this issue, the documentation just talks a lot about `registry.hub.docker.io` (emphasis on `io`), and it talks about it as if it's the default URL for the Docker registry (particularly that second quote in the original comment gave me that impression). But it seems to me now that this is not a valid URL for a Docker registry, rather `registry.hub.docker.com` is. Is it meant as a URL, in which case I'd say *that's wrong*, or is it meant as an identifier of some sort?

**Comment by rhuss** [comment] 2015-05-15 19:15
I see your point for 1), that's indeed a bug.

For 2), the server ID is in fact meant as an real IP addrress, not only an alias. `registry.hub.docker.io` however is somewhat special since it was used for looking up auth info in case *no* registry has been provided. Where the actual push is going to when no registry is used is the duty of the Docker daemon. So, yes, for the default `registry.hub.docker.io` is special and not really used except for the association with the auth information. For all others registries they are used as well for pushing (also, interpreted by the Docker daemon which in contacts the registry) and for looking up auth information.

But at the end I think it boil down to issue #146, when this is fixed things should be much more transparent. 

And you are right, `registry.hub.docker.io` should be `registry.hub.docker.com`. I will this (but keep for backwards compatibility the lookup to `registry.hub.docker.io` as a fallback)

**Comment by sverhagen** [comment] 2015-05-17 08:31
I may want to open a separate issue for this...

> Where the actual push is going to when no registry is used is the duty of the Docker daemon

We are moving our CI server over from a Debian-based machine to CentOS, and all of a sudden my build is broken. Apparently Docker on CentOS comes with a different set of default registries (registry) than my Ubuntu. Now, isn't Maven all about consistent, reproducible builds? I would argue that leaving it up to the Docker daemon is "not done" in *Maven land*. Require users to be specific, or at least spit out a warning when no registry is specified.

**Comment by rhuss** [comment] 2015-05-18 11:50
Internally I just found out, that at least my Docker installations treats 'index.docker.io' as the default. E.g. ty to tag an existant image without registry into the index.docker.io namespace:

     docker pull busybox
     docker tag busybox index.docker.io/busybox

You will get an error, that the tags already exists. That clearly indicates that index.docker.io is the implicit default.

However if you try to run 

    docker run -it index.docker.io/busybox bash

You get an error here, too. All strange.

I think, if all things working as descibed in the plugin, which shouldn't be too harsh. It's about reproducible builds, yes, but at some point there is a limit. E.g. you also can't guarantee that the artefacts you download as dependencies (maybe through an proxy ?) are the same. It's good to have the possibility to nail down the registry, but otherwise I tend to be liberal because that makes things simpler. Also, having a different default registry than registry.hub.docker.com should be the exception.

**Comment by sverhagen** [comment] 2015-05-19 07:57
I'm fine with that :smile:

Just as an observation, wouldn't many companies set up Docker registries internally and wanting to default to that, in a similar fashion how many organizations have their own Maven repository?

`fixed`, is that still in respect to the following?

> And you are right, registry.hub.docker.io should be registry.hub.docker.com. I will change this

**Comment by rhuss** [comment] 2015-05-19 08:18
/wrt a defaul registry: Yes, you are probably right and I think the possibility to use a global configuration property (outside of all image declaration) or as an environment variable fits this need properly.

The `fixed` means that the lookup in settings.xml should work regardless whether the registry is provided as an extra config option or as part of an image name (that was a bug) and that the documentation has been fixed with respect to the name of the default registry.

**Closed** 2015-05-22 13:50 UTC
Labels: bug, fixed
