### ISSUE TITLE
Randomly assign internal/external port together

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#150] opened 2015-04-29 19:22 UTC
This is a question. I'm looking for a way to have a port dynamically assigned, both internally and externally. So where we would normally define stanzas like so:

    <port>OUTSIDE:INSIDE</port>

And consequently:

    <port>${OUTSIDE}:INSIDE</port>

I would like to be able to do something like this:

    <port>${OUTSIDE}:${OUTSIDE}</port>
    <port>${OUTSIDE}</port>

In other words: I want a port dynamically assigned (so that I can have multiple containers of the same image running on the same system without port conflicts) that has its internal port the same number as the external port (because the service that runs in the container uses the port number in its handshaking, does not understand the external/internal concepts, and thus does not work with external/internal different port numbers).

I can see how this is possibly a Docker limitation more than it is a Docker Maven plugin limitation, but I figured I'd ask :smile: Your help would be appreciated.

**Comment by akobiakov** [comment] 2015-05-06 15:16
@sverhagen Have you tried [build-helper-plugin](http://mojo.codehaus.org/build-helper-maven-plugin/reserve-network-port-mojo.html)?

**Comment by sverhagen** [comment] 2015-05-06 19:38
I think that would not work: we need to determine a port on the Docker host, not on the machine that's running Maven. While that's sometimes the same thing... certainly not always. If we were able to determine a port, I'd be curious if it's actually possible to pass in the internal port, the right-hand side of the stanza.

**Comment by rhuss** [comment] 2015-05-18 18:32
Your are right, I think that's not possible because the apps **inside** the container don't have any knowledge how they look from the **outside** (and that's by design a good thing in order to avoid dependencies in the wrong direction). The question also is, how to communicate the dynamically allocated, inside port to your service so that it becomes aware of this ?

Sorry, I'm out of ideas here and since this is really not an issue of the plugin but of Docker itself or the setup, I'd like to close the issue. Feel free to reopen it, if you still think we could do something about with the plugin.

**Closed by rhuss** 2015-05-18 18:32 UTC

**Comment by chris-snider** [comment] 2015-05-18 18:47
I have seen references to including the docker client inside the container.  This allows the container to interrogate the docker host for information via the docker inspect <container name>.  This requires the container to have a known name both inside and out however.

**Note** I have not tried this technique myself.

**Comment by rhuss** [comment] 2015-05-18 18:52
Indeed, I've seen this 'wormwhole' approach also several times, mostly by sharing Docker unix socket as a volume. 

But that doesn't help since the container is already setup to export a fixed (not dynamically chosen) internal port to a dynamically chosen external port. This internal port cannot be changed in retrospective AFAIK. Docker has no possibility to dynamically choose the *internal* port. You probably need something of a filter which rewrites the port for the handshake. This filter then could use the technique described by @chris-snider to determine the external visible port for translation.

**Comment by chris-snider** [comment] 2015-05-18 19:18
We have used environment variables to pass the expected external ports into the executing container which are then sed'd into appropriate files.  In our case, it is spring property files using the systemEnvironment values.  Since our containers are registering with a service discovery/registry system, we can maintain the internal ports as hard coded, SSL ports for example, and use the provided external ports to post to the service discovery.

We still have to maintain the external port listing.  However, this is where the 'wormhole' (I like that term) would come in handy since the container has the container ID provided in an environment variable such as

container_uuid=4f79dea7-1da9-b493-4796-b058e595a38a

Strip the hyphens and you have the first portion of the container.

If you use the externally applied port gained from the introspection of the container_uuid, and leave the internal ports hard-coded to appropriate values, then during the startup script, you apply the external port to the service registration and leave the internal port alone.  The docker daemon will handle the port forwarding of the external port to the internal port and the container is really none-the-wiser.

**Comment by sverhagen** [comment] 2015-05-18 19:26
This is Hazelcast, and as far as I have researched it, so far, it has a (fixed) signaling port, through which it tells the (external) client what the number is of the (other) port that the client has to connect to next. This port may be dynamic, but can also be set to a fixed (internal) port, but whatever the client gets from Hazelcast does then not match the dynamic and mapped external port.

**Comment by rhuss** [comment] 2015-05-18 19:47
Arrgh, and I thought RMI with its handshake was the worst protocol. Handshake based protocol where ports are negotiated are always hard to deal with.

Maybe you find some hints for this issue by looking for how Hazelcast deals with NAT setups (which I are a bit similar, not for ports, but for IP addresses). If it is flexbile enought it should allow to configure how it announces its external view for the handshake (i.e. setting the signaling port to use for the handshake different to the actual port). If not, I think an issue should be raised, otherwise Hazelcast is not really usable within Docker containers.

**Comment by sverhagen** [comment] 2015-05-19 07:51
I can probably get away here with linking containers. I'm only recently scratching the surface of that feature (linking; and kudos on how the plugin deals with that, it's above expectations), and it's unclear to me whether linking container A into container B means that B can connect A on any port. If so, B could connect A on the (fixed) signaling port, then on whatever other port it desires. Or is linking limited to just the ports that are otherwise already exposed?
